### PR TITLE
Add note in README about native support in Vim/Neovim

### LINKED ISSUE #3: Integrate natively with vim
It would be great to see if we could add this feature natively into vim so it could have less overhead and fewer quirks. I filed FR vim/vim#453 in the vim tracker to request it.

### PR DESCRIPTION
**Pull request by dbarnett**
Fixes #3.

### CODE REVIEW

**Comment by lmintmate** [comment]
As an (until just now) user of vim-searchindex, maybe it would be a good idea to also specify in that note in the README that the option that does this in vim is `set shortmess-=S`. I suggest this because I was baffled for a few seconds about how I could possibly enable this, and only found out the solution by going [at the issue you link to here](https://github.com/google/vim-searchindex/issues/3), and from there [to the issue in the vim repo you mention at the OP of issue 3](https://github.com/vim/vim/issues/453), and from there scrolling down all the way [until here](https://github.com/vim/vim/issues/453#issuecomment-489510217). Not very discoverable imo.
Thank you in advance for the understanding.

P.S. If I understood correctly however, this is on the contrary the default behavior on neovim, and a user of that one doesn't need to set anything else. I found this out by looking first [at this post from the issue you linked to](https://github.com/google/vim-searchindex/issues/3#issuecomment-494247671), and from there [this issue](https://github.com/neovim/neovim/issues/10041) which links to a neovim PR that is referenced by [this here neovim PR](https://github.com/neovim/neovim/pull/10136) which removes S from the shortmess. Again not very discoverable, hence this should probably also be specified on the README.

**Comment by rburny** [comment]
Agreed with @lmintmate. Can you please add this note (or some link to the documentation)?

**Comment by dbarnett** [comment]
> Agreed with @lmintmate. Can you please add this note (or some link to the documentation)?

Good point. I wasn't actually aware of the caveats. Is this version good?

**Comment by rburny** [comment]
Looks good. BTW, another caveat of the native version is that it has an arbitrary restriction to 99 matches. But the benefits of using native functionality probably outweigh these tiny issues.

**Comment by dbarnett** [comment]
Huh, that's… bizarre. Do you have a pointer to details?

**Comment by rburny** [comment]
Take a look at the patch:
https://github.com/vim/vim/commit/9dfa3139198b38b28673e251a3756430065914e9#diff-c5fd2d4520848f3908f309cb45abbc9eR4990

This semantics is documented in runtime/doc/pattern.txt, and the implementation hardcodes the constant "99" in multiple places. This was present since the early version of the patch, so I guess it's author's preference that no one challenged.

**Pull request merged**
